version: '3'

services:
  mgenode0:
    container_name: mgenode0
    image: "mage/magenode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-mge.log}
    volumes:
      - ./build:/mge:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  mgenode1:
    container_name: mgenode1
    image: "mage/magenode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-mge.log}
    volumes:
      - ./build:/mge:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  mgenode2:
    container_name: mgenode2
    image: "mage/magenode"
    environment:
      - ID=2
      - LOG=${LOG:-mge.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/mge:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  mgenode3:
    container_name: mgenode3
    image: "mage/magenode"
    environment:
      - ID=3
      - LOG=${LOG:-mge.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/mge:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
